services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    ports:
      - ${MAILDEV_WEB_PORT}:1080

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - ${RABBITMQ_WEB_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    restart: unless-stopped
    ports:
      - "${API_GATEWAY__PORT}:${API_GATEWAY__PORT}"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  identity_service:
    container_name: identity_service
    build:
      context: .
      dockerfile: ./apps/identity/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

  notification_service:
    container_name: notification_service
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - maildev

volumes:
  postgres_data:
  rabbitmq_data: