services:
  public_proxy:
    image: nginx:latest
    container_name: public_proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    depends_on:
      rabbitmq:
        condition: service_healthy
      maildev:
        condition: service_healthy
      api-gateway:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1080"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  identity_service:
    container_name: identity_service
    build:
      context: .
      dockerfile: ./apps/identity/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  notification_service:
    container_name: notification_service
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      maildev:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: