services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: api-gateway
      IDENTITY__HOST: identity
    ports:
      - "${API_GATEWAY__PORT}:${API_GATEWAY__PORT}"
    depends_on:
      - postgres

  identity:
    container_name: identity
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: identity
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: identity
    ports:
      - "${IDENTITY__PORT}:${IDENTITY__PORT}"
    depends_on:
      - postgres

volumes:
  postgres_data: